const names = require('./names')
const utils = require('./utils')
const altnames = require('./altnames')
// const mg = require('./mg')
console.log(altnames.names)
console.log(altnames.person)
console.log(names)
utils.sayHi('susan')
utils.sayHi(names.john)
utils.sayHi(names.peter)